#!/usr/bin/env python


"""
Autogenerated by CHEETAH: The Python-Powered Template Engine
 CHEETAH VERSION: 0.9.16b1
 Generation time: Sun May 15 19:59:47 2005
   Source file: request_details.tmpl
   Source file last modified: Sun May 15 19:57:33 2005
"""

__CHEETAH_genTime__ = 'Sun May 15 19:59:47 2005'
__CHEETAH_src__ = 'request_details.tmpl'
__CHEETAH_version__ = '0.9.16b1'

##################################################
## DEPENDENCIES

import sys
import os
import os.path
from os.path import getmtime, exists
import time
import types
import __builtin__
from Cheetah.Template import Template
from Cheetah.DummyTransaction import DummyTransaction
from Cheetah.NameMapper import NotFound, valueForName, valueFromFrameOrSearchList
import Cheetah.Filters as Filters
import Cheetah.ErrorCatchers as ErrorCatchers
from _layout import _layout

##################################################
## MODULE CONSTANTS

try:
    True, False
except NameError:
    True, False = (1==1), (1==0)
VFFSL=valueFromFrameOrSearchList
VFN=valueForName
currentTime=time.time

##################################################
## CLASSES

class request_details(_layout):
    """
    
    Autogenerated by CHEETAH: The Python-Powered Template Engine
    """

    ##################################################
    ## GENERATED METHODS


    def __init__(self, *args, **KWs):
        """
        
        """

        _layout.__init__(self, *args, **KWs)

    def title(self,
            trans=None,
            dummyTrans=False,
            VFFSL=valueFromFrameOrSearchList,
            VFN=valueForName,
            getmtime=getmtime,
            currentTime=time.time):


        """
        Generated from #def title at line 4, col 1.
        """

        if not trans:
            trans = DummyTransaction()
            dummyTrans = True
        write = trans.response().write
        SL = self._searchList
        filter = self._currentFilter
        globalSetVars = self._globalSetVars
        
        ########################################
        ## START - generated method body
        
        write('Request Details')
        
        ########################################
        ## END - generated method body
        
        if dummyTrans:
            return trans.response().getvalue()
        else:
            return ""
        

    def body(self,
            trans=None,
            dummyTrans=False,
            VFFSL=valueFromFrameOrSearchList,
            VFN=valueForName,
            getmtime=getmtime,
            currentTime=time.time):


        """
        This is the main method generated by Cheetah
        """

        if not trans:
            trans = DummyTransaction()
            dummyTrans = True
        write = trans.response().write
        SL = self._searchList
        filter = self._currentFilter
        globalSetVars = self._globalSetVars
        
        ########################################
        ## START - generated method body
        
        write('''

<p>
<h2>Request Object</h2>
<table>

<thead>
  <tr>
    <td><strong>Key</strong></td>
    <td><strong>Value</strong></td>
  </tr>
</thead>

<tbody>
  <tr><td>args</td><td>''')
        write(filter(VFFSL(SL,"self.req.args",True), rawExpr='$self.req.args')) # from line 20, col 24.
        write('</td></tr>\n  <tr><td>hostname</td><td>')
        write(filter(VFFSL(SL,"self.req.hostname",True), rawExpr='$self.req.hostname')) # from line 21, col 28.
        write('</td></tr>\n  <tr><td>interpreter</td><td>')
        write(filter(VFFSL(SL,"self.req.interpreter",True), rawExpr='$self.req.interpreter')) # from line 22, col 31.
        write('</td></tr>\n  <tr><td>method</td><td>')
        write(filter(VFFSL(SL,"self.req.method",True), rawExpr='$self.req.method')) # from line 23, col 26.
        write('</td></tr>\n  <tr><td>path_info</td><td>')
        write(filter(VFFSL(SL,"self.req.path_info",True), rawExpr='$self.req.path_info')) # from line 24, col 29.
        write('</td></tr>\n  <tr><td>proto_num</td><td>')
        write(filter(VFFSL(SL,"self.req.proto_num",True), rawExpr='$self.req.proto_num')) # from line 25, col 29.
        write('</td></tr>\n  <tr><td>protocol</td><td>')
        write(filter(VFFSL(SL,"self.req.protocol",True), rawExpr='$self.req.protocol')) # from line 26, col 28.
        write('</td></tr>\n  <tr><td>the_request</td><td>')
        write(filter(VFFSL(SL,"self.req.the_request",True), rawExpr='$self.req.the_request')) # from line 27, col 31.
        write('</td></tr>\n  <tr><td>unparsed_uri</td><td>')
        write(filter(VFFSL(SL,"self.req.unparsed_uri",True), rawExpr='$self.req.unparsed_uri')) # from line 28, col 32.
        write('</td></tr>\n  <tr><td>uri</td><td>')
        write(filter(VFFSL(SL,"self.req.uri",True), rawExpr='$self.req.uri')) # from line 29, col 23.
        write('</td></tr>\n  <tr><td>user</td><td>')
        write(filter(VFFSL(SL,"self.req.user",True), rawExpr='$self.req.user')) # from line 30, col 24.
        write('''</td></tr></tr>
</tbody>

</table>
</p>

''')
        headers = VFFSL(SL,"req.headers_in",True)
        keys = VFN(VFFSL(SL,"headers",True),"keys",False)()
        VFN(VFFSL(SL,"keys",True),"sort",False)()
        write('''
<p>
<h2>Request Headers</h2>
<table>

<thead>
  <tr>
    <td><strong>Key</strong></td>
    <td><strong>Value</strong></td>
  </tr>
</thead>

<tbody>
''')
        for key in VFFSL(SL,"keys",True):
            write('  <tr>\n    <td>')
            write(filter(VFFSL(SL,"key",True), rawExpr='$key')) # from line 54, col 9.
            write('</td>\n    <td>')
            write(filter(VFFSL(SL,"headers",True)[VFFSL(SL,"key",True)], rawExpr='$headers[$key]')) # from line 55, col 9.
            write('</td>\n  </tr>\n')
        write('''</tbody>

</table>
</p>
''')
        
        ########################################
        ## END - generated method body
        
        if dummyTrans:
            return trans.response().getvalue()
        else:
            return ""
        
    ##################################################
    ## GENERATED ATTRIBUTES


    _mainCheetahMethod_for_request_details= 'body'


# CHEETAH was developed by Tavis Rudd, Mike Orr, Ian Bicking and Chuck Esterbrook;
# with code, advice and input from many other volunteers.
# For more information visit http://www.CheetahTemplate.org

##################################################
## if run from command line:
if __name__ == '__main__':
    request_details().runAsMainProgram()

